package com.group30.daily_reading_track.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

// make this class connect to the database
@Entity // Able to connect the database, inside the Admin table
public class Admin {
    private String username;
    private String password;
    private String Email;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // unique id generated by database
    private int Id; // Become the id of table and have unique id
    
    //constructor with no argument
    public Admin(){
    }

    public Admin(String username, String password, String Email){
        this.username = username;
        this.password = password;
        this. Email = Email;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String email) {
        Email = email;
    }

    public int getId() {
        return Id;
    }

    public void setId(int id) {
        Id = id;
    }

    
}
